### ISSUE TITLE
Reach = crash

### ISSUE THREAD

**Issue by DUELPVP** [PianoPenguin471/RavenWeave#35] opened 2023-07-08 15:15 UTC
toggle reach with release 1.1.3 will result a crash

**Comment by Sweet-Tooth11** [comment] 2023-07-08 15:38
I can confirm this crash. Here's a stacktrace:

[2023-07-08 17:30:34.727] [info]  [OUTPUT] [17:30:34] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "ravenweave.client.module.modules.combat.KillAura.isEnabled()" because "ravenweave.client.module.modules.combat.Reach.killAura" is null
	at ravenweave.client.module.modules.combat.Reach.getReach(Reach.java:30) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java:4044) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1563) ~[?:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1377) ~[?:?]
	at net.minecraft.client.Minecraft.runGameLoop(SourceFile:915) ~[?:?]
	at net.minecraft.client.Minecraft.run(SourceFile:325) [?:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at com.moonsworth.lunar.genesis.Genesis.main(Unknown Source) [genesis-0.1.0-SNAPSHOT-all.jar:?]


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at Genesis//ravenweave.client.module.modules.combat.Reach.getReach(Reach.java:30)
	at Genesis//net.minecraft.client.renderer.EntityRenderer.getMouseOver(EntityRenderer.java:4044)
	at Genesis//net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1563)

**Comment by Zircta** [comment] 2023-07-10 19:06
this just doesn't happen to me 😭, but i'll try to fix it

**Comment by Zircta** [comment] 2023-07-11 00:15
unable to reproduce, if someone can show a video that would be helpful

**Comment by ncwo** [comment] 2023-07-11 04:33
was it working in earlier versions?
i had the same issue because i was using an outdated version of lunar

what are you using to launch it?

**Comment by Zircta** [comment] 2023-07-11 06:06
Someone who experiences this crash please provide a video, operating system, and method of launching (e.g. weave manager, lcqt, etc).

**Comment by ncwo** [comment] 2023-07-11 09:35
[lunarcmd](https://github.com/GameParrot/lunarcmd) is what i was using when i had this issue, but switching to lcqt fixed it

**Comment by god86521** [comment] 2023-07-12 04:53
the same just happend to me

**Comment by god86521** [comment] 2023-07-12 04:53
i crashed for turning on reach

**Comment by Cosmic-SC** [comment] 2023-07-13 05:28
> unable to reproduce, if someone can show a video that would be helpful

easy fix ill do it

**Comment by Cosmic-SC** [comment] 2023-07-13 05:28
its just a null pointer

**Comment by Zircta** [comment] 2023-07-14 07:51
Should be fixed in the lastest commit (thanks to [Cosmic-SC](https://github.com/Cosmic-SC)), check out [actions](https://github.com/PianoPenguin471/RavenWeave/actions) for the latest build.

**Closed by Zircta** 2023-07-14 07:51 UTC

**Comment by DUELPVP** [comment] 2023-07-14 07:54
Idk how to use it. Please upload a new release

**Comment by Zircta** [comment] 2023-07-14 09:54
> Idk how to use it. Please upload a new release

Go [here](https://github.com/PianoPenguin471/RavenWeave/actions/runs/5550306207) and click the "compiled" under "Artifacts".
